### ISSUE TITLE
从页面上发出我说的内容的时候就卡住了， Cannot connect to host speech.platform.bing.com，但实际上是通的

### ISSUE THREAD

**Issue by modiao2018** [yakami129/VirtualWife#38]
这个是爱莉的性格简述：可爱，善良，健谈，有很多话题可以谈论，活泼，容易被惊艳。
爱莉的记忆:
The current time of the system is 2023-09-25 15:50:59,your response should consider this information
Respond in spoken, colloquial and short Simplified Chinese and do not mention any rules of character.
<</SYS>>
yuki129说你叫什么名字[/INST]
INFO:root:prompt:
    <s>[INST] <<SYS>>
    You are now an emotion expression AI, this is my text, please speculate on the emotion the text wants to express,
    The rules for expressing emotions are as follows: There are five types of feelings that express normal "neutral", "happy" that expresses happiness, "angry" that expresses anger, "sad" that expresses sadness, and "relaxed" that expresses calm. Your result can only be one of these five
    
    Please output the result in all lowercase letters.
    Please only output the result, no need to output the reasoning process.
    Please use the output of your reasoning emotion.
    Please output the result strictly in JSON format. The output example is as follows:
    {"emote":"your reasoning emotions"}
    <</SYS>>
    text:小蜜蜂告诉我,她刚刚在路上遇到一团奇怪的迷雾,导致消息晚点到达,请耐心等待[/INST]
INFO:django.channels.server:HTTP POST /chatbot/chat 200 [44.89, 172.18.0.3:44152]
INFO:django.channels.server:HTTP GET /chatbot/customrole/vrmmodel/list 200 [0.01, 172.18.0.3:44172]
INFO:django.channels.server:HTTP GET /chatbot/customrole/list 200 [0.02, 172.18.0.3:44174]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/edge-tts", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/edge_tts/util.py", line 137, in main
    loop.run_until_complete(amain())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/edge_tts/util.py", line 130, in amain
    await _run_tts(args)
  File "/usr/local/lib/python3.10/site-packages/edge_tts/util.py", line 65, in _run_tts
    async for chunk in tts.stream():
  File "/usr/local/lib/python3.10/site-packages/edge_tts/communicate.py", line 309, in stream
    async with aiohttp.ClientSession(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host speech.platform.bing.com:443 ssl:<ssl.SSLContext object at 0x7f066a827f40> [Temporary failure in name resolution]
INFO:django.channels.server:HTTP POST /speech/tts/generate 200 [16.26, 172.18.0.3:44166]

**Comment by yakami129** [comment]
speech.platform.bing.com 是你的代理吗？
