### ISSUE TITLE
哔哩哔哩字幕初始化失败

### ISSUE THREAD

**Issue by xinzhics** [yakami129/VirtualWife#70]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[INFO][2023-11-30 07:30:05,784][bili_live_client.py:121] 	 => Start BiliLiveClient Success
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
[INFO][2023-11-30 07:30:05,785][realtime_message_queue.py:108] 	 => Start RealtimeMessageQueryJobTask Success
[INFO][2023-11-30 07:30:05,786][chat_history_queue.py:71] 	 => Start ChatHistoryMessageQueryJobTask Success
    self._target(*self._args, **self._kwargs)
  File "/app/apps/chatbot/insight/bilibili/bili_live_client.py", line 125, in start_bili_live_client
[INFO][2023-11-30 07:30:05,786][insight_message_queue.py:76] 	 => Start InsightMessageQueryJobTask Success
    client = BiliLiveClient()
  File "/app/apps/chatbot/insight/bilibili/bili_live_client.py", line 30, in __init__
    self.uid = int(uid)
ValueError: invalid literal for int() with base 10: '38ccccc'

**Comment by yakami129** [comment]
FAQ有解决方案：

https://github.com/yakami129/VirtualWife/blob/main/FAQ.md
